services:
  redis:
    image: redis:8.8-alpine

  publisher:
    image: publisher
    depends_on:
      - redis
    ports:
      - "8001:8001"
    
  subscriber:
    image: subscriber
    depends_on:
      - redis
    ports:
      - "8002:8002"