services:
  redis:
    image: redis:8.8-alpine

  publisher:
    build: 
      context: ./publisher
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8001:8001"
    
  subscriber:
    build: 
      context: ./subscriber
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8002:8002"